/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/laptopScreen.glb
*/

import { Html, useGLTF } from '@react-three/drei';
import React, { useEffect, useState } from 'react';

export function LaptopScreen(props) {
  const { nodes } = useGLTF('./models/laptopScreen.glb');

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.laptop_screen.geometry}
        material={nodes.laptop_screen.material}
      >
      </mesh>
    </group>
  );
}

useGLTF.preload('./models/laptopScreen.glb');
