/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/monitorScreen.glb 
*/

import { useGLTF, useVideoTexture } from '@react-three/drei';
import React from 'react';

export function MonitorScreen(props) {
  const { nodes } = useGLTF('./models/monitorScreen.glb');
  const textureMonitor = useVideoTexture('./textures/monitor_screen.mp4');

  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          geometry={nodes.monitor_screen.geometry}
          material={nodes.monitor_screen.material}
        >
          <meshBasicMaterial map={textureMonitor} toneMapped={false} />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('./models/monitorScreen.glb');
